image: node:14

stages:
  - deploy

deploy:
  stage: deploy
  script:
    #- echo "//gitlab.fantasia.dev/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
