image: node:14

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "@crosshair-code-generator:registry=https://gitlab.fantasia.dev/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//gitlab.fantasia.dev/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
