interface Crosshair {
  gap: number,
  outlineThickness: number,
  r: number,
  g: number,
  b: number,
  alpha: number,
  outline: boolean,
  color: number,
  thickness: number,
  t: boolean,
  useAlpha: boolean,
  useWeaponValue: boolean,
  dot: boolean,
  style: number,
  size: number,
}
